-- Wires up the batch-2 destination cover photos (see
-- design/destination-photo-prompts-batch2.json and lib/destinationPhotos.ts)
-- to every city that was still missing one, plus the 14 cities added in
-- migration_037. Only touches rows that are still null, so it's safe to
-- re-run and won't clobber a manually-picked photo.
update cities as c set cover_photo_id = v.id
from (values
  ('Abu Dhabi', 'abu-dhabi'),
  ('Agra', 'agra'),
  ('Amman', 'amman'),
  ('Andorra la Vella', 'andorra-la-vella'),
  ('Auckland', 'auckland'),
  ('Austin', 'austin'),
  ('Baku', 'baku'),
  ('Bath', 'bath'),
  ('Beirut', 'beirut'),
  ('Bilbao', 'bilbao'),
  ('Bogota', 'bogota'),
  ('Bologna', 'bologna'),
  ('Bordeaux', 'bordeaux'),
  ('Bratislava', 'bratislava'),
  ('Brisbane', 'brisbane'),
  ('Buenos Aires', 'buenos-aires'),
  ('Busan', 'busan'),
  ('Cagliari', 'cagliari'),
  ('Cairo', 'cairo'),
  ('Cambridge', 'cambridge'),
  ('Cancun', 'cancun'),
  ('Cape Town', 'cape-town'),
  ('Cartagena', 'cartagena'),
  ('Casablanca', 'casablanca'),
  ('Cebu', 'cebu'),
  ('Cesky Krumlov', 'cesky-krumlov'),
  ('Charleston', 'charleston'),
  ('Colombo', 'colombo'),
  ('Corfu', 'corfu'),
  ('Cusco', 'cusco'),
  ('Delhi', 'delhi'),
  ('Denver', 'denver'),
  ('Doha', 'doha'),
  ('Eilat', 'eilat'),
  ('Fes', 'fes'),
  ('Gdansk', 'gdansk'),
  ('Goa', 'goa'),
  ('Granada', 'granada'),
  ('Hanoi', 'hanoi'),
  ('Havana', 'havana'),
  ('Heraklion', 'heraklion'),
  ('Ho Chi Minh City', 'ho-chi-minh-city'),
  ('Jaipur', 'jaipur'),
  ('Jeddah', 'jeddah'),
  ('Jeju', 'jeju'),
  ('Jerusalem', 'jerusalem'),
  ('Johannesburg', 'johannesburg'),
  ('Kathmandu', 'kathmandu'),
  ('Kuala Lumpur', 'kuala-lumpur'),
  ('Kuwait City', 'kuwait-city'),
  ('Kyiv', 'kyiv'),
  ('Langkawi', 'langkawi'),
  ('Larnaca', 'larnaca'),
  ('Lima', 'lima'),
  ('Liverpool', 'liverpool'),
  ('Luxembourg City', 'luxembourg-city'),
  ('Luxor', 'luxor'),
  ('Malaga', 'malaga'),
  ('Male', 'male'),
  ('Manama', 'manama'),
  ('Manchester', 'manchester'),
  ('Manila', 'manila'),
  ('Marrakech', 'marrakech'),
  ('Marseille', 'marseille'),
  ('Melbourne', 'melbourne'),
  ('Mexico City', 'mexico-city'),
  ('Monaco', 'monaco'),
  ('Montreal', 'montreal'),
  ('Mumbai', 'mumbai'),
  ('Muscat', 'muscat'),
  ('Nadi', 'nadi'),
  ('Nairobi', 'nairobi'),
  ('Napa Valley', 'napa-valley'),
  ('Oxford', 'oxford'),
  ('Palermo', 'palermo'),
  ('Palm Springs', 'palm-springs'),
  ('Petra', 'petra'),
  ('Philadelphia', 'philadelphia'),
  ('Phnom Penh', 'phnom-penh'),
  ('Pisa', 'pisa'),
  ('Portland', 'portland'),
  ('Poznan', 'poznan'),
  ('Quebec City', 'quebec-city'),
  ('Queenstown', 'queenstown'),
  ('Quito', 'quito'),
  ('Rhodes', 'rhodes'),
  ('Rio de Janeiro', 'rio-de-janeiro'),
  ('Riyadh', 'riyadh'),
  ('San Juan', 'san-juan'),
  ('San Sebastian', 'san-sebastian'),
  ('Santiago', 'santiago'),
  ('Sao Paulo', 'sao-paulo'),
  ('Savannah', 'savannah'),
  ('Siem Reap', 'siem-reap'),
  ('Strasbourg', 'strasbourg'),
  ('Sydney', 'sydney'),
  ('Taipei', 'taipei'),
  ('Tbilisi', 'tbilisi'),
  ('Tel Aviv', 'tel-aviv'),
  ('Thessaloniki', 'thessaloniki'),
  ('Toronto', 'toronto'),
  ('Tulum', 'tulum'),
  ('Tunis', 'tunis'),
  ('Turin', 'turin'),
  ('Vancouver', 'vancouver'),
  ('Verona', 'verona'),
  ('Victoria Falls', 'victoria-falls'),
  ('Wroclaw', 'wroclaw'),
  ('Yerevan', 'yerevan'),
  ('Zanzibar', 'zanzibar'),
  ('Southampton', 'southampton'),
  ('Vigo', 'vigo'),
  ('La Coruña', 'la-coruna'),
  ('Antwerp', 'antwerp'),
  ('Basel', 'basel'),
  ('Faro', 'faro'),
  ('Belfast', 'belfast'),
  ('Sarajevo', 'sarajevo'),
  ('Yellowstone National Park', 'yellowstone-national-park'),
  ('Yosemite National Park', 'yosemite-national-park'),
  ('Key West', 'key-west'),
  ('Maui', 'maui'),
  ('Anchorage', 'anchorage'),
  ('Niagara Falls', 'niagara-falls')
) as v(name, id)
where c.name = v.name and c.cover_photo_id is null;
