import { ImageSourcePropType } from "react-native";

// Bundled destination cover photos. Metro needs static `require(...)` calls
// (no dynamic paths), so every photo has to be listed explicitly here — this
// is also the full list the cover-photo picker shows. See
// design/destination-photo-prompts.json (original set) and
// design/destination-photo-prompts-batch2.json (v44 addition) for the
// id/city/country mapping if the photo set changes again.
export const DEFAULT_COVER_PHOTO_ID = "_fallback";

export interface DestinationPhoto {
  id: string;
  city: string;
  country: string;
  source: ImageSourcePropType;
}

export const DESTINATION_PHOTOS: DestinationPhoto[] = [
  { id: "paris", city: "Paris", country: "France", source: require("../assets/destinations/paris.jpg") },
  { id: "london", city: "London", country: "United Kingdom", source: require("../assets/destinations/london.jpg") },
  { id: "rome", city: "Rome", country: "Italy", source: require("../assets/destinations/rome.jpg") },
  { id: "venice", city: "Venice", country: "Italy", source: require("../assets/destinations/venice.jpg") },
  { id: "florence", city: "Florence", country: "Italy", source: require("../assets/destinations/florence.jpg") },
  { id: "milan", city: "Milan", country: "Italy", source: require("../assets/destinations/milan.jpg") },
  { id: "naples", city: "Naples", country: "Italy", source: require("../assets/destinations/naples.jpg") },
  { id: "cinque-terre", city: "Cinque Terre", country: "Italy", source: require("../assets/destinations/cinque-terre.jpg") },
  { id: "amalfi-coast", city: "Amalfi Coast", country: "Italy", source: require("../assets/destinations/amalfi-coast.jpg") },
  { id: "barcelona", city: "Barcelona", country: "Spain", source: require("../assets/destinations/barcelona.jpg") },
  { id: "madrid", city: "Madrid", country: "Spain", source: require("../assets/destinations/madrid.jpg") },
  { id: "seville", city: "Seville", country: "Spain", source: require("../assets/destinations/seville.jpg") },
  { id: "valencia", city: "Valencia", country: "Spain", source: require("../assets/destinations/valencia.jpg") },
  { id: "palma-de-mallorca", city: "Palma de Mallorca", country: "Spain", source: require("../assets/destinations/palma-de-mallorca.jpg") },
  { id: "ibiza", city: "Ibiza", country: "Spain", source: require("../assets/destinations/ibiza.jpg") },
  { id: "lisbon", city: "Lisbon", country: "Portugal", source: require("../assets/destinations/lisbon.jpg") },
  { id: "porto", city: "Porto", country: "Portugal", source: require("../assets/destinations/porto.jpg") },
  { id: "berlin", city: "Berlin", country: "Germany", source: require("../assets/destinations/berlin.jpg") },
  { id: "munich", city: "Munich", country: "Germany", source: require("../assets/destinations/munich.jpg") },
  { id: "hamburg", city: "Hamburg", country: "Germany", source: require("../assets/destinations/hamburg.jpg") },
  { id: "cologne", city: "Cologne", country: "Germany", source: require("../assets/destinations/cologne.jpg") },
  { id: "frankfurt", city: "Frankfurt", country: "Germany", source: require("../assets/destinations/frankfurt.jpg") },
  { id: "amsterdam", city: "Amsterdam", country: "Netherlands", source: require("../assets/destinations/amsterdam.jpg") },
  { id: "rotterdam", city: "Rotterdam", country: "Netherlands", source: require("../assets/destinations/rotterdam.jpg") },
  { id: "brussels", city: "Brussels", country: "Belgium", source: require("../assets/destinations/brussels.jpg") },
  { id: "bruges", city: "Bruges", country: "Belgium", source: require("../assets/destinations/bruges.jpg") },
  { id: "vienna", city: "Vienna", country: "Austria", source: require("../assets/destinations/vienna.jpg") },
  { id: "salzburg", city: "Salzburg", country: "Austria", source: require("../assets/destinations/salzburg.jpg") },
  { id: "innsbruck", city: "Innsbruck", country: "Austria", source: require("../assets/destinations/innsbruck.jpg") },
  { id: "zurich", city: "Zurich", country: "Switzerland", source: require("../assets/destinations/zurich.jpg") },
  { id: "geneva", city: "Geneva", country: "Switzerland", source: require("../assets/destinations/geneva.jpg") },
  { id: "prague", city: "Prague", country: "Czech Republic", source: require("../assets/destinations/prague.jpg") },
  { id: "budapest", city: "Budapest", country: "Hungary", source: require("../assets/destinations/budapest.jpg") },
  { id: "warsaw", city: "Warsaw", country: "Poland", source: require("../assets/destinations/warsaw.jpg") },
  { id: "krakow", city: "Krakow", country: "Poland", source: require("../assets/destinations/krakow.jpg") },
  { id: "vilnius", city: "Vilnius", country: "Lithuania", source: require("../assets/destinations/vilnius.jpg") },
  { id: "riga", city: "Riga", country: "Latvia", source: require("../assets/destinations/riga.jpg") },
  { id: "tallinn", city: "Tallinn", country: "Estonia", source: require("../assets/destinations/tallinn.jpg") },
  { id: "copenhagen", city: "Copenhagen", country: "Denmark", source: require("../assets/destinations/copenhagen.jpg") },
  { id: "stockholm", city: "Stockholm", country: "Sweden", source: require("../assets/destinations/stockholm.jpg") },
  { id: "gothenburg", city: "Gothenburg", country: "Sweden", source: require("../assets/destinations/gothenburg.jpg") },
  { id: "oslo", city: "Oslo", country: "Norway", source: require("../assets/destinations/oslo.jpg") },
  { id: "bergen", city: "Bergen", country: "Norway", source: require("../assets/destinations/bergen.jpg") },
  { id: "helsinki", city: "Helsinki", country: "Finland", source: require("../assets/destinations/helsinki.jpg") },
  { id: "reykjavik", city: "Reykjavik", country: "Iceland", source: require("../assets/destinations/reykjavik.jpg") },
  { id: "dublin", city: "Dublin", country: "Ireland", source: require("../assets/destinations/dublin.jpg") },
  { id: "edinburgh", city: "Edinburgh", country: "United Kingdom", source: require("../assets/destinations/edinburgh.jpg") },
  { id: "athens", city: "Athens", country: "Greece", source: require("../assets/destinations/athens.jpg") },
  { id: "santorini", city: "Santorini", country: "Greece", source: require("../assets/destinations/santorini.jpg") },
  { id: "mykonos", city: "Mykonos", country: "Greece", source: require("../assets/destinations/mykonos.jpg") },
  { id: "dubrovnik", city: "Dubrovnik", country: "Croatia", source: require("../assets/destinations/dubrovnik.jpg") },
  { id: "split", city: "Split", country: "Croatia", source: require("../assets/destinations/split.jpg") },
  { id: "ljubljana", city: "Ljubljana", country: "Slovenia", source: require("../assets/destinations/ljubljana.jpg") },
  { id: "zagreb", city: "Zagreb", country: "Croatia", source: require("../assets/destinations/zagreb.jpg") },
  { id: "belgrade", city: "Belgrade", country: "Serbia", source: require("../assets/destinations/belgrade.jpg") },
  { id: "bucharest", city: "Bucharest", country: "Romania", source: require("../assets/destinations/bucharest.jpg") },
  { id: "sofia", city: "Sofia", country: "Bulgaria", source: require("../assets/destinations/sofia.jpg") },
  { id: "istanbul", city: "Istanbul", country: "Turkey", source: require("../assets/destinations/istanbul.jpg") },
  { id: "antalya", city: "Antalya", country: "Turkey", source: require("../assets/destinations/antalya.jpg") },
  { id: "cappadocia", city: "Cappadocia", country: "Turkey", source: require("../assets/destinations/cappadocia.jpg") },
  { id: "valletta", city: "Valletta", country: "Malta", source: require("../assets/destinations/valletta.jpg") },
  { id: "nice", city: "Nice", country: "France", source: require("../assets/destinations/nice.jpg") },
  { id: "new-york-city", city: "New York City", country: "United States", source: require("../assets/destinations/new-york-city.jpg") },
  { id: "los-angeles", city: "Los Angeles", country: "United States", source: require("../assets/destinations/los-angeles.jpg") },
  { id: "san-francisco", city: "San Francisco", country: "United States", source: require("../assets/destinations/san-francisco.jpg") },
  { id: "las-vegas", city: "Las Vegas", country: "United States", source: require("../assets/destinations/las-vegas.jpg") },
  { id: "miami", city: "Miami", country: "United States", source: require("../assets/destinations/miami.jpg") },
  { id: "chicago", city: "Chicago", country: "United States", source: require("../assets/destinations/chicago.jpg") },
  { id: "washington-dc", city: "Washington DC", country: "United States", source: require("../assets/destinations/washington-dc.jpg") },
  { id: "boston", city: "Boston", country: "United States", source: require("../assets/destinations/boston.jpg") },
  { id: "seattle", city: "Seattle", country: "United States", source: require("../assets/destinations/seattle.jpg") },
  { id: "orlando", city: "Orlando", country: "United States", source: require("../assets/destinations/orlando.jpg") },
  { id: "new-orleans", city: "New Orleans", country: "United States", source: require("../assets/destinations/new-orleans.jpg") },
  { id: "honolulu", city: "Honolulu", country: "United States", source: require("../assets/destinations/honolulu.jpg") },
  { id: "san-diego", city: "San Diego", country: "United States", source: require("../assets/destinations/san-diego.jpg") },
  { id: "nashville", city: "Nashville", country: "United States", source: require("../assets/destinations/nashville.jpg") },
  { id: "grand-canyon", city: "Grand Canyon", country: "United States", source: require("../assets/destinations/grand-canyon.jpg") },
  { id: "tokyo", city: "Tokyo", country: "Japan", source: require("../assets/destinations/tokyo.jpg") },
  { id: "kyoto", city: "Kyoto", country: "Japan", source: require("../assets/destinations/kyoto.jpg") },
  { id: "osaka", city: "Osaka", country: "Japan", source: require("../assets/destinations/osaka.jpg") },
  { id: "hakone", city: "Hakone", country: "Japan", source: require("../assets/destinations/hakone.jpg") },
  { id: "sapporo", city: "Sapporo", country: "Japan", source: require("../assets/destinations/sapporo.jpg") },
  { id: "nara", city: "Nara", country: "Japan", source: require("../assets/destinations/nara.jpg") },
  { id: "hiroshima", city: "Hiroshima", country: "Japan", source: require("../assets/destinations/hiroshima.jpg") },
  { id: "beijing", city: "Beijing", country: "China", source: require("../assets/destinations/beijing.jpg") },
  { id: "shanghai", city: "Shanghai", country: "China", source: require("../assets/destinations/shanghai.jpg") },
  { id: "hong-kong", city: "Hong Kong", country: "China", source: require("../assets/destinations/hong-kong.jpg") },
  { id: "guilin", city: "Guilin", country: "China", source: require("../assets/destinations/guilin.jpg") },
  { id: "xi-an", city: "Xi'an", country: "China", source: require("../assets/destinations/xi-an.jpg") },
  { id: "chengdu", city: "Chengdu", country: "China", source: require("../assets/destinations/chengdu.jpg") },
  { id: "bangkok", city: "Bangkok", country: "Thailand", source: require("../assets/destinations/bangkok.jpg") },
  { id: "phuket", city: "Phuket", country: "Thailand", source: require("../assets/destinations/phuket.jpg") },
  { id: "chiang-mai", city: "Chiang Mai", country: "Thailand", source: require("../assets/destinations/chiang-mai.jpg") },
  { id: "krabi", city: "Krabi", country: "Thailand", source: require("../assets/destinations/krabi.jpg") },
  { id: "koh-samui", city: "Koh Samui", country: "Thailand", source: require("../assets/destinations/koh-samui.jpg") },
  { id: "singapore", city: "Singapore", country: "Singapore", source: require("../assets/destinations/singapore.jpg") },
  { id: "seoul", city: "Seoul", country: "South Korea", source: require("../assets/destinations/seoul.jpg") },
  { id: "bali", city: "Bali", country: "Indonesia", source: require("../assets/destinations/bali.jpg") },
  { id: "dubai", city: "Dubai", country: "United Arab Emirates", source: require("../assets/destinations/dubai.jpg") },
  { id: "ha-long-bay", city: "Ha Long Bay", country: "Vietnam", source: require("../assets/destinations/ha-long-bay.jpg") },
  { id: "lyon", city: "Lyon", country: "France", source: require("../assets/destinations/lyon.jpg") },
  // Not a real place — a cruise's "day at sea", so a trip whose primary
  // destination is mostly a cruise can pick this as its cover instead of
  // whatever port city happens to be first. See migration_036 for the
  // matching `cities` row.
  { id: "at-sea", city: "At Sea", country: "International Waters", source: require("../assets/destinations/at-sea.jpg") },

  // Batch 2 — see design/destination-photo-prompts-batch2.json. Covers every
  // city added to the `cities` catalog that still had no cover photo, plus
  // the new cities added alongside it (the v44 cruise-port batch).
  { id: "abu-dhabi", city: "Abu Dhabi", country: "United Arab Emirates", source: require("../assets/destinations/abu-dhabi.jpg") },
  { id: "agra", city: "Agra", country: "India", source: require("../assets/destinations/agra.jpg") },
  { id: "amman", city: "Amman", country: "Jordan", source: require("../assets/destinations/amman.jpg") },
  { id: "andorra-la-vella", city: "Andorra la Vella", country: "Andorra", source: require("../assets/destinations/andorra-la-vella.jpg") },
  { id: "auckland", city: "Auckland", country: "New Zealand", source: require("../assets/destinations/auckland.jpg") },
  { id: "austin", city: "Austin", country: "United States", source: require("../assets/destinations/austin.jpg") },
  { id: "baku", city: "Baku", country: "Azerbaijan", source: require("../assets/destinations/baku.jpg") },
  { id: "bath", city: "Bath", country: "United Kingdom", source: require("../assets/destinations/bath.jpg") },
  { id: "beirut", city: "Beirut", country: "Lebanon", source: require("../assets/destinations/beirut.jpg") },
  { id: "bilbao", city: "Bilbao", country: "Spain", source: require("../assets/destinations/bilbao.jpg") },
  { id: "bogota", city: "Bogota", country: "Colombia", source: require("../assets/destinations/bogota.jpg") },
  { id: "bologna", city: "Bologna", country: "Italy", source: require("../assets/destinations/bologna.jpg") },
  { id: "bordeaux", city: "Bordeaux", country: "France", source: require("../assets/destinations/bordeaux.jpg") },
  { id: "bratislava", city: "Bratislava", country: "Slovakia", source: require("../assets/destinations/bratislava.jpg") },
  { id: "brisbane", city: "Brisbane", country: "Australia", source: require("../assets/destinations/brisbane.jpg") },
  { id: "buenos-aires", city: "Buenos Aires", country: "Argentina", source: require("../assets/destinations/buenos-aires.jpg") },
  { id: "busan", city: "Busan", country: "South Korea", source: require("../assets/destinations/busan.jpg") },
  { id: "cagliari", city: "Cagliari", country: "Italy", source: require("../assets/destinations/cagliari.jpg") },
  { id: "cairo", city: "Cairo", country: "Egypt", source: require("../assets/destinations/cairo.jpg") },
  { id: "cambridge", city: "Cambridge", country: "United Kingdom", source: require("../assets/destinations/cambridge.jpg") },
  { id: "cancun", city: "Cancun", country: "Mexico", source: require("../assets/destinations/cancun.jpg") },
  { id: "cape-town", city: "Cape Town", country: "South Africa", source: require("../assets/destinations/cape-town.jpg") },
  { id: "cartagena", city: "Cartagena", country: "Colombia", source: require("../assets/destinations/cartagena.jpg") },
  { id: "casablanca", city: "Casablanca", country: "Morocco", source: require("../assets/destinations/casablanca.jpg") },
  { id: "cebu", city: "Cebu", country: "Philippines", source: require("../assets/destinations/cebu.jpg") },
  { id: "cesky-krumlov", city: "Cesky Krumlov", country: "Czech Republic", source: require("../assets/destinations/cesky-krumlov.jpg") },
  { id: "charleston", city: "Charleston", country: "United States", source: require("../assets/destinations/charleston.jpg") },
  { id: "colombo", city: "Colombo", country: "Sri Lanka", source: require("../assets/destinations/colombo.jpg") },
  { id: "corfu", city: "Corfu", country: "Greece", source: require("../assets/destinations/corfu.jpg") },
  { id: "cusco", city: "Cusco", country: "Peru", source: require("../assets/destinations/cusco.jpg") },
  { id: "delhi", city: "Delhi", country: "India", source: require("../assets/destinations/delhi.jpg") },
  { id: "denver", city: "Denver", country: "United States", source: require("../assets/destinations/denver.jpg") },
  { id: "doha", city: "Doha", country: "Qatar", source: require("../assets/destinations/doha.jpg") },
  { id: "eilat", city: "Eilat", country: "Israel", source: require("../assets/destinations/eilat.jpg") },
  { id: "fes", city: "Fes", country: "Morocco", source: require("../assets/destinations/fes.jpg") },
  { id: "gdansk", city: "Gdansk", country: "Poland", source: require("../assets/destinations/gdansk.jpg") },
  { id: "goa", city: "Goa", country: "India", source: require("../assets/destinations/goa.jpg") },
  { id: "granada", city: "Granada", country: "Spain", source: require("../assets/destinations/granada.jpg") },
  { id: "hanoi", city: "Hanoi", country: "Vietnam", source: require("../assets/destinations/hanoi.jpg") },
  { id: "havana", city: "Havana", country: "Cuba", source: require("../assets/destinations/havana.jpg") },
  { id: "heraklion", city: "Heraklion", country: "Greece", source: require("../assets/destinations/heraklion.jpg") },
  { id: "ho-chi-minh-city", city: "Ho Chi Minh City", country: "Vietnam", source: require("../assets/destinations/ho-chi-minh-city.jpg") },
  { id: "jaipur", city: "Jaipur", country: "India", source: require("../assets/destinations/jaipur.jpg") },
  { id: "jeddah", city: "Jeddah", country: "Saudi Arabia", source: require("../assets/destinations/jeddah.jpg") },
  { id: "jeju", city: "Jeju", country: "South Korea", source: require("../assets/destinations/jeju.jpg") },
  { id: "jerusalem", city: "Jerusalem", country: "Israel", source: require("../assets/destinations/jerusalem.jpg") },
  { id: "johannesburg", city: "Johannesburg", country: "South Africa", source: require("../assets/destinations/johannesburg.jpg") },
  { id: "kathmandu", city: "Kathmandu", country: "Nepal", source: require("../assets/destinations/kathmandu.jpg") },
  { id: "kuala-lumpur", city: "Kuala Lumpur", country: "Malaysia", source: require("../assets/destinations/kuala-lumpur.jpg") },
  { id: "kuwait-city", city: "Kuwait City", country: "Kuwait", source: require("../assets/destinations/kuwait-city.jpg") },
  { id: "kyiv", city: "Kyiv", country: "Ukraine", source: require("../assets/destinations/kyiv.jpg") },
  { id: "langkawi", city: "Langkawi", country: "Malaysia", source: require("../assets/destinations/langkawi.jpg") },
  { id: "larnaca", city: "Larnaca", country: "Cyprus", source: require("../assets/destinations/larnaca.jpg") },
  { id: "lima", city: "Lima", country: "Peru", source: require("../assets/destinations/lima.jpg") },
  { id: "liverpool", city: "Liverpool", country: "United Kingdom", source: require("../assets/destinations/liverpool.jpg") },
  { id: "luxembourg-city", city: "Luxembourg City", country: "Luxembourg", source: require("../assets/destinations/luxembourg-city.jpg") },
  { id: "luxor", city: "Luxor", country: "Egypt", source: require("../assets/destinations/luxor.jpg") },
  { id: "malaga", city: "Malaga", country: "Spain", source: require("../assets/destinations/malaga.jpg") },
  { id: "male", city: "Male", country: "Maldives", source: require("../assets/destinations/male.jpg") },
  { id: "manama", city: "Manama", country: "Bahrain", source: require("../assets/destinations/manama.jpg") },
  { id: "manchester", city: "Manchester", country: "United Kingdom", source: require("../assets/destinations/manchester.jpg") },
  { id: "manila", city: "Manila", country: "Philippines", source: require("../assets/destinations/manila.jpg") },
  { id: "marrakech", city: "Marrakech", country: "Morocco", source: require("../assets/destinations/marrakech.jpg") },
  { id: "marseille", city: "Marseille", country: "France", source: require("../assets/destinations/marseille.jpg") },
  { id: "melbourne", city: "Melbourne", country: "Australia", source: require("../assets/destinations/melbourne.jpg") },
  { id: "mexico-city", city: "Mexico City", country: "Mexico", source: require("../assets/destinations/mexico-city.jpg") },
  { id: "monaco", city: "Monaco", country: "Monaco", source: require("../assets/destinations/monaco.jpg") },
  { id: "montreal", city: "Montreal", country: "Canada", source: require("../assets/destinations/montreal.jpg") },
  { id: "mumbai", city: "Mumbai", country: "India", source: require("../assets/destinations/mumbai.jpg") },
  { id: "muscat", city: "Muscat", country: "Oman", source: require("../assets/destinations/muscat.jpg") },
  { id: "nadi", city: "Nadi", country: "Fiji", source: require("../assets/destinations/nadi.jpg") },
  { id: "nairobi", city: "Nairobi", country: "Kenya", source: require("../assets/destinations/nairobi.jpg") },
  { id: "napa-valley", city: "Napa Valley", country: "United States", source: require("../assets/destinations/napa-valley.jpg") },
  { id: "oxford", city: "Oxford", country: "United Kingdom", source: require("../assets/destinations/oxford.jpg") },
  { id: "palermo", city: "Palermo", country: "Italy", source: require("../assets/destinations/palermo.jpg") },
  { id: "palm-springs", city: "Palm Springs", country: "United States", source: require("../assets/destinations/palm-springs.jpg") },
  { id: "petra", city: "Petra", country: "Jordan", source: require("../assets/destinations/petra.jpg") },
  { id: "philadelphia", city: "Philadelphia", country: "United States", source: require("../assets/destinations/philadelphia.jpg") },
  { id: "phnom-penh", city: "Phnom Penh", country: "Cambodia", source: require("../assets/destinations/phnom-penh.jpg") },
  { id: "pisa", city: "Pisa", country: "Italy", source: require("../assets/destinations/pisa.jpg") },
  { id: "portland", city: "Portland", country: "United States", source: require("../assets/destinations/portland.jpg") },
  { id: "poznan", city: "Poznan", country: "Poland", source: require("../assets/destinations/poznan.jpg") },
  { id: "quebec-city", city: "Quebec City", country: "Canada", source: require("../assets/destinations/quebec-city.jpg") },
  { id: "queenstown", city: "Queenstown", country: "New Zealand", source: require("../assets/destinations/queenstown.jpg") },
  { id: "quito", city: "Quito", country: "Ecuador", source: require("../assets/destinations/quito.jpg") },
  { id: "rhodes", city: "Rhodes", country: "Greece", source: require("../assets/destinations/rhodes.jpg") },
  { id: "rio-de-janeiro", city: "Rio de Janeiro", country: "Brazil", source: require("../assets/destinations/rio-de-janeiro.jpg") },
  { id: "riyadh", city: "Riyadh", country: "Saudi Arabia", source: require("../assets/destinations/riyadh.jpg") },
  { id: "san-juan", city: "San Juan", country: "Puerto Rico", source: require("../assets/destinations/san-juan.jpg") },
  { id: "san-sebastian", city: "San Sebastian", country: "Spain", source: require("../assets/destinations/san-sebastian.jpg") },
  { id: "santiago", city: "Santiago", country: "Chile", source: require("../assets/destinations/santiago.jpg") },
  { id: "sao-paulo", city: "Sao Paulo", country: "Brazil", source: require("../assets/destinations/sao-paulo.jpg") },
  { id: "savannah", city: "Savannah", country: "United States", source: require("../assets/destinations/savannah.jpg") },
  { id: "siem-reap", city: "Siem Reap", country: "Cambodia", source: require("../assets/destinations/siem-reap.jpg") },
  { id: "strasbourg", city: "Strasbourg", country: "France", source: require("../assets/destinations/strasbourg.jpg") },
  { id: "sydney", city: "Sydney", country: "Australia", source: require("../assets/destinations/sydney.jpg") },
  { id: "taipei", city: "Taipei", country: "Taiwan", source: require("../assets/destinations/taipei.jpg") },
  { id: "tbilisi", city: "Tbilisi", country: "Georgia", source: require("../assets/destinations/tbilisi.jpg") },
  { id: "tel-aviv", city: "Tel Aviv", country: "Israel", source: require("../assets/destinations/tel-aviv.jpg") },
  { id: "thessaloniki", city: "Thessaloniki", country: "Greece", source: require("../assets/destinations/thessaloniki.jpg") },
  { id: "toronto", city: "Toronto", country: "Canada", source: require("../assets/destinations/toronto.jpg") },
  { id: "tulum", city: "Tulum", country: "Mexico", source: require("../assets/destinations/tulum.jpg") },
  { id: "tunis", city: "Tunis", country: "Tunisia", source: require("../assets/destinations/tunis.jpg") },
  { id: "turin", city: "Turin", country: "Italy", source: require("../assets/destinations/turin.jpg") },
  { id: "vancouver", city: "Vancouver", country: "Canada", source: require("../assets/destinations/vancouver.jpg") },
  { id: "verona", city: "Verona", country: "Italy", source: require("../assets/destinations/verona.jpg") },
  { id: "victoria-falls", city: "Victoria Falls", country: "Zimbabwe", source: require("../assets/destinations/victoria-falls.jpg") },
  { id: "wroclaw", city: "Wroclaw", country: "Poland", source: require("../assets/destinations/wroclaw.jpg") },
  { id: "yerevan", city: "Yerevan", country: "Armenia", source: require("../assets/destinations/yerevan.jpg") },
  { id: "zanzibar", city: "Zanzibar", country: "Tanzania", source: require("../assets/destinations/zanzibar.jpg") },
  { id: "southampton", city: "Southampton", country: "United Kingdom", source: require("../assets/destinations/southampton.jpg") },
  { id: "vigo", city: "Vigo", country: "Spain", source: require("../assets/destinations/vigo.jpg") },
  { id: "la-coruna", city: "La Coruña", country: "Spain", source: require("../assets/destinations/la-coruna.jpg") },
  { id: "antwerp", city: "Antwerp", country: "Belgium", source: require("../assets/destinations/antwerp.jpg") },
  { id: "basel", city: "Basel", country: "Switzerland", source: require("../assets/destinations/basel.jpg") },
  { id: "faro", city: "Faro", country: "Portugal", source: require("../assets/destinations/faro.jpg") },
  { id: "belfast", city: "Belfast", country: "United Kingdom", source: require("../assets/destinations/belfast.jpg") },
  { id: "sarajevo", city: "Sarajevo", country: "Bosnia and Herzegovina", source: require("../assets/destinations/sarajevo.jpg") },
  { id: "yellowstone-national-park", city: "Yellowstone National Park", country: "United States", source: require("../assets/destinations/yellowstone-national-park.jpg") },
  { id: "yosemite-national-park", city: "Yosemite National Park", country: "United States", source: require("../assets/destinations/yosemite-national-park.jpg") },
  { id: "key-west", city: "Key West", country: "United States", source: require("../assets/destinations/key-west.jpg") },
  { id: "maui", city: "Maui", country: "United States", source: require("../assets/destinations/maui.jpg") },
  { id: "anchorage", city: "Anchorage", country: "United States", source: require("../assets/destinations/anchorage.jpg") },
  { id: "niagara-falls", city: "Niagara Falls", country: "United States", source: require("../assets/destinations/niagara-falls.jpg") },
];

export const FALLBACK_COVER_PHOTO: ImageSourcePropType = require("../assets/destinations/_fallback.jpg");

/** Resolves a trip's stored cover_photo_id to an actual image source, falling
 * back to the generic placeholder if unset or if that photo no longer exists
 * (e.g. the set gets pruned/renamed later). */
export function coverPhotoSource(coverPhotoId: string | null | undefined): ImageSourcePropType {
  const match = coverPhotoId ? DESTINATION_PHOTOS.find((p) => p.id === coverPhotoId) : undefined;
  return match ? match.source : FALLBACK_COVER_PHOTO;
}

export function searchDestinationPhotos(query: string): DestinationPhoto[] {
  const q = query.trim().toLowerCase();
  if (!q) return DESTINATION_PHOTOS;
  return DESTINATION_PHOTOS.filter(
    (p) => p.city.toLowerCase().includes(q) || p.country.toLowerCase().includes(q)
  );
}
